### ISSUE TITLE
Implement grouping as per v1.7.

### ISSUE THREAD

**Issue by jeff-h** [pascalpp/FreeRuler#10]
Assuming you're thinking of just two rulers at this stage, in a nutshell I think it will involve:

* a boolean on the `AppDelegate`
* capturing the window movement from each window controller's `NSWindowDelegate` extension, and passing it back up to the AppDelegate. Something roughly like:
    ````swift
    extension RulerHorizontalWindow: NSWindowDelegate {
    
        ...
    
        func windowDidMove(_ notification: Notification) {
            let appDelegate = NSApplication.shared.delegate as? AppDelegate
            appDelegate?.windowDidMove(notification)
        }
    }
* having the AppDelegate "choreograph" the synchronisation of the two windows' positions, by implementing its own homegrown version of `windowDidMove`, as called by the two windows as per above . 

You'd likely need to:

* get the window out of the notification (`guard let window = notification.object as? NSWindow` or similar)
* somehow identify which window triggered the window move (a switch or something checking for `window.windowController as? RulerHorizontalWindow` perhaps?)
* then adjust the other window's frame

Please let me know which parts of the above make no sense whatsoever! :)

**Comment by jeff-h** [comment]
Oh and one other thing, adding a menu item to swap the boolean :)

* add a method to the AppDelegate; something like `@IBAction func groupRulers(_ sender: Any)`
* in `MainMenu.xib` > drag in a new `NSMenuItem`, control-click it and connect its action to the "First Responder" in Placeholders. You should be able to connect it then to the `groupRulers` method.

**Comment by pascalpp** [comment]
Awesome, thanks so much for the pointers!

**Comment by pascalpp** [comment]
working on this now. I've figured out a way to know which window triggered the move, but still trying to figure out a couple things:

- not sure how to tell how far the window moved in the windowDidMove handler. One option would be to stash the window.frame.origin when windowWillMove is triggered. But that event is only triggered when the window is moved via the mouse, not when using the keyboard nudge methods. Maybe could call appDelegate.windowWillMove manually in the keyboard listeners?

- the .window property of each ruler instance is alway nil. (The alphaValue changes are having no effect for the same reason.) This has something to do with the window being loaded from the nib files, but I don't fully understand this process yet.

**Comment by pascalpp** [comment]
(figured out the nil window issue; the referencing outlet for window wasn't hooked up to File's Owner. (I still only sort of understand how this works, but I figured this out by creating a new NSWindowController class and xib and compared each panel in the inspector.)

**Comment by jeff-h** [comment]
Wow, you sure had to jump through some hoops to get that functional. I was feeling quite sure there must be a nicer way so I dived in and and yet, here I am an hour later still banging my head on the wall!

Cocoa can sometimes be a right pain :(

**Comment by jeff-h** [comment]
I've created a PR which simplifies the grouping code somewhat. Please feel free to poke at it, take some or all of it, or throw it away :)

https://github.com/pascalpp/FreeRuler/pull/13

**Comment by pascalpp** [comment]
Sweet I’ll have a look later today!

**Comment by pascalpp** [comment]
Copied from that PR:

I think I want to keep grouping decoupled from window position as in version 1.x, so rulers could be moved as a group without modifying the distance between them. And we'll add a separate command to align the rulers at the cursor location, same as 1.x. Also I want to explore removing the rounded corners on the windows.

**Comment by pascalpp** [comment]
Wondering if there’s a way to mirror the original mouse down event into the other window so it _thinks_ it’s getting moved as well..

Another crazy idea would be to have a single transparent window with two ruler views inside it, and somehow let clicks in that window pass through unless they land on one of the ruler views.

**Comment by pascalpp** [comment]
This looks promising https://developer.apple.com/documentation/appkit/nsevent/1534971-addlocalmonitorforevents

**Comment by jeff-h** [comment]
Ha, I totally missed that in v1 you can group the rulers but not have them touching. That does complicate it somewhat but in my version I suppose on mousedown you could store their offsets and use that inside `moveWith()`. I think I was instinctively trying to minimise the number of things being done during a drag, in the hopes the performance might improve (but it didn't).

**Comment by jeff-h** [comment]
> Another crazy idea would be to have a single transparent window

I actually downloaded a ruler app from the MAS recently which did this. I disliked it, but don't recall the details unfortunately. I will take another look when I have a chance.

**Comment by pascalpp** [comment]
Yeah unfortunately the most recent source code I have is only 1.2, in the legacy branch. The implementation will be totally different of course, but lemme see if we can extrapolate from the technique used there.

**Comment by pascalpp** [comment]
```
hRuler.MouseDrag:
Sub MouseDrag(X As Integer, Y As Integer)
  self.left = self.left + x - MouseDownX
  self.top = self.top + y - MouseDownY
  
  if OptionsGroupRulers.checked then
    vRuler.left = vRuler.left + x - MouseDownX
    vRuler.top = vRuler.top + y - MouseDownY
  end
End Sub
```

So looks like each ruler implements it’s own drag handler, and each ruler has a reference to the other ruler, and each ruler knows if grouped is true or false.

**Comment by pascalpp** [comment]
Maybe the app can have its own drag handler and manage moving both windows if grouped, or just the target window if not grouped. And maybe we can move the key press handling to the app as well.

**Comment by jeff-h** [comment]
Cool, thanks for digging into that. I was rather hoping it might illuminate another possibility but all it does is add to my current Cocoa frustration :) Although no doubt it's my knowledge of Cocoa at fault.

**Comment by jeff-h** [comment]
Sounds like a good possibility. I have had trouble getting the mouse events (`mouseUp`, `mouseDown` etc) firing on the window; as in the current code they seem to fire no problems on the view in the window though, so I guess we could control it all from there.

**Comment by jeff-h** [comment]
I just remembered, one problem with implementing our own window drag handling is how it breaks a bunch of OS functions around changing spaces eg dragging a window to the edge of the screen should allow you to move it to other spaces. Not a deal-breaker I guess, particularly since v1.x has the same limitation and I've never noticed it till now :)

**Comment by pascalpp** [comment]
![image](https://user-images.githubusercontent.com/1355312/56843204-9f9a7500-686b-11e9-877a-5263c36fb4ac.png)

Tinkering with the window shape in this branch. Kinda wonder if we really need close buttons on the rulers. @jeff-h what do you think?

**Comment by jeff-h** [comment]
Beautiful! I've personally never "closed" a ruler in 1.7. TBH the visual styling of the close button was the main reason I went with an NSPanel, so if it's all easier as a plain `NSWindow` certainly go that way.

**Comment by jeff-h** [comment]
I've been digging into CoreAnimation to see if that will provide smoother window linking. Unfortunately my implementation of CA to link the windows had exactly the same lagginess, but I did find https://github.com/jwilling/JNWAnimatableWindow which looks like it might hold some clues.

**Comment by pascalpp** [comment]
Yeah I'm thinking we'll have menu items to toggle the windows (along with H and V shortcuts), so it'll still be possible to close them.

**Comment by pascalpp** [comment]
Found a cool project with various window style demos: https://github.com/lukakerr/NSWindowStyles

So I'm cribbing some stuff from there to get the window appearance we want.

**Comment by jeff-h** [comment]
Nice find!

**Comment by pascalpp** [comment]
Made some progress. Was struggling with the canBecomeKey property being coerced to false when i removed the titlebar (which has to be removed in order to get rid of the rounded corners). Finally figured out we can subclass NSPanel and override that property to always be true. (After googling that idea, found confirmation here: https://soffes.blog/cancel-borderless-window).

I also noticed that moving hWindow would call vWindow's moveWIth method, which would trigger a new windowDidMove event and would then call hWindow's moveWIth method, which was a no-op since the window was already at the desired location, but wasted cycles nonetheless. So I added a guard so that only the key window will trigger synchronize. And I let each window controller implement its own moveWith method so the rules abut just like in v1.7.

**Comment by pascalpp** [comment]
Oh and I started stubbing out some prefs stuff so the value of groupRulers is persisted.

**Comment by pascalpp** [comment]
Currently stumped on NSPanel.isFloatingPanel. If I hide the title bar (in order to get rid of the rounded corners), then that property is coerced to false, so the rulers don't stay on top when switching to another application. Trying to figure out how to override that. I have the horizontal rule with title disabled, and the vertical ruler with it on. The horizontal ruler has window.isFloatingPanel as false and it doesn't float; the vertical one has window.isFloatingPanel as true and it does float.

If I override isFloatingPanel:

```
class RulerWindow: NSPanel {
    
    override var canBecomeKey: Bool {
        return true
    }

    override var isFloatingPanel: Bool {
        get {
            return true
        }
        set {
            return
        }
    }
}
```

...they both report it as true but neither floats. Hmmph.

**Comment by pascalpp** [comment]
hey @jeff-h check this out:

![childwindow mov](https://user-images.githubusercontent.com/1355312/57173200-100c3d80-6dfa-11e9-943d-5a9fb81d785c.gif)

I spent the last week taking a couple different Swift/AppKit development courses, and I found [this article](https://www.bignerdranch.com/blog/nswindow-an-introduction/) on creating NSWindows programmatically (no xib files), so I started a new project from scratch. Something about having a xib file backing the window was blocking me from overrwiting isFloatingPanel, whereas I can do it freely if I create the window myself. And then I found [this StackOverflow question](https://stackoverflow.com/questions/13472299/how-to-tie-nswindow-to-another-nswindow) on moving windows in sync, which points to window.addChildWindow, and came up with this. Hopefully I can have each ruler window become the parent window when it's clicked, so that moving either ruler will move the other one in sync. Once I get that working I'll port this solution into the grouping branch and integrate the view drawing code.

**Comment by jeff-h** [comment]
Fantastic! You should be pretty chuffed by that :)

**Comment by pascalpp** [comment]
yer such a brit

**Comment by jeff-h** [comment]
lol indeed (albeit about 180° off)

**Comment by pascalpp** [comment]
Oh oops! Australia? New Zealand?

**Comment by pascalpp** [comment]
@jeff-h I've pushed the latest in the grouping branch if you wanna try it out.

**Comment by pascalpp** [comment]
For future reference: https://stackoverflow.com/questions/34538112/nswindowcontroller-without-a-nib-file-in-swift#34538897
