### ISSUE TITLE
You show the rulers in an angle, how to do that?

### ISSUE THREAD

**Issue by Chacapamac** [pascalpp/FreeRuler#106]
I download your app (which works flawlessly on Mac OS Sierra) to measure an angle. I was sure to be able to do that as you show the ruler in an angle position.

I didn’t see how on your documentation?

![Screen Shot 2022-05-31 at 9 03 40 AM](https://user-images.githubusercontent.com/1907276/171180236-ab799b40-815e-4166-9526-033e984354ad.jpg)

**Comment by pascalpp** [comment]
Sorry Free Ruler does not measure angles. That's just the icon design, cribbing from the angled icon style of previous versions of Mac OS (which has since fallen out of favor with Apple). 

For reference, on the left are angled icons from Mac OS Catalina, on the right are squarish icons from Mac OS Big Sur.
![](https://ijunkie.com/wp-content/uploads/2020/07/Apple-macOS-Catalina-vs-macOS-Big-Sur-02-scaled.jpg)
